version: "3.8"

services:
  dwp-assessment-go:
    image: ${GITHUB_IMAGE:-dwp-assessment-go:local}
    build:
      context: .
    container_name: dwp-assessment-go
    depends_on:
      wiremock:
        condition: service_healthy
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      CONFIGURATION_PATH: ./configuration.yaml
      PORT: ${PORT:-8080}
      CONTEXT_PATH: ${CONTEXT_PATH:-/}
      PEOPLE_ENDPOINT: ${PEOPLE_ENDPOINT:-http://wiremock:8080}
      MAX_DISTANCE: ${MAX_DISTANCE:-50}

  wiremock:
    image: wiremock/wiremock:2.32.0-alpine
    container_name: wiremock
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
    command: --verbose
    ports:
      - "8090:8080"
    volumes:
      - ./wiremock/files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings

  api-tests:
    image: golang:1.18.2
    container_name: api-tests
    depends_on:
      dwp-assessment-go:
        condition: service_healthy
    working_dir: /src
    command: go test -v -tags=component ./api-tests
    environment:
      BASE_URL: http://dwp-assessment-go:${PORT:-8080}
    volumes:
      - ./:/src
